name: Python running script

# on:
#   schedule:
#     - cron: '0 */12 * * *'
  

# on:
#   schedule:
#     - cron: '23 11 * * *'

on:
  workflow_dispatch: 

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'


      - name: Running ishika python script
        run: python test.py
